return {
	misc = {
		dictionary = {
			k_multiplayer = 'Multiplayer',
			k_status_offline = 'Offline',
			k_status_connecting = 'Connecting...',
			k_status_signing_in = 'Signing In...',
			k_status_connected = 'Connected',
			k_your_avatar_cap_1 = 'YOUR',
			k_your_avatar_cap_2 = 'AVATAR',
			k_click_to_change = 'Click to Change',
			k_dev_mode_suffix = '(Dev)',
			k_not_linked = 'Not Linked',
			k_multiplayer_account = 'Multiplayer Account',
			k_id = 'ID',
			k_steam_username = 'Steam Username',
			k_discord_username = 'Discord Username',
			k_display_name = 'Display Name',
			k_steam = 'Steam',
			k_discord = 'Discord',
			k_link_discord = 'Link Discord',
			k_unlink_discord = 'Unlink Discord',
			b_open_download_page = 'Open Download Page',
			b_retry_connection = 'Retry Connection',
		},
	},
}
