return {
	misc = {
		dictionary = {
			k_multiplayer = 'Multiplayer',
			k_status_offline = 'Offline',
			k_status_connecting = 'Connecting...',
			k_status_signing_in = 'Signing In...',
			k_status_connected = 'Connected',
			k_your_avatar_cap_1 = 'YOUR',
			k_your_avatar_cap_2 = 'AVATAR',
			k_click_to_change = 'Click to Change',
			k_dev_mode_suffix = '(Dev)',
			k_not_linked = 'Not Linked',
			k_multiplayer_account = 'Multiplayer Account',
			k_id = 'ID',
			k_steam_username = 'Steam Username',
			k_discord_username = 'Discord Username',
			k_display_name = 'Display Name',
			k_auto_login = 'Auto Login',
			k_steam = 'Steam',
			k_discord = 'Discord',
			k_link_discord = 'Link Discord',
			k_unlink_discord = 'Unlink Discord',
			k_tos_title = 'Terms of Service & Privacy Policy',
			k_tos_first_time_1 = 'By accepting, you will register an account with',
			k_tos_first_time_2 = 'Balatro Multiplayer using your Steam account.',
			k_tos_first_time_3 = 'Please read and accept the Terms of Service and Privacy Policy.',
			k_tos_update_1 = 'The Terms of Service and Privacy Policy have been updated.',
			k_tos_update_2 = 'Please review and accept them to continue.',
			b_open_download_page = 'Open Download Page',
			b_retry_connection = 'Retry Connection',
			b_log_in = 'Log In',
			b_view_tos = 'View Terms of Service',
			b_view_privacy = 'View Privacy Policy',
			b_i_accept = 'I Accept',
			b_i_decline = 'I Decline',
			b_create_lobby_cap = { 'CREATE', 'LOBBY' },
			b_join_lobby_cap = 'JOIN LOBBY',
			b_by_code_cap = 'BY CODE',
			b_from_clipboard_cap = 'FROM CLIPBOARD',
			b_find_game_cap = 'FIND GAME',
			b_open_lobby_cap = { 'OPEN', 'LOBBY' },
			b_lobby_options_cap = { 'LOBBY', 'OPTIONS' },
			b_leave_lobby_cap = { 'LEAVE', 'LOBBY' },
		},
	},
}
