return {
	misc = {
		dictionary = {
			k_multiplayer = 'Multiplayer',
			k_status_offline = 'Offline',
			k_status_connecting = 'Connecting...',
			k_status_signing_in = 'Signing In...',
			k_status_connected = 'Connected',
			k_your_avatar_cap_1 = 'YOUR',
			k_your_avatar_cap_2 = 'AVATAR',
			k_click_to_change = 'Click to Change',
			k_dev_mode_suffix = '(Dev)',
			k_not_linked = 'Not Linked',
			k_multiplayer_account = 'Multiplayer Account',
			k_id = 'ID',
			k_steam_username = 'Steam Username',
			k_discord_username = 'Discord Username',
			k_display_name = 'Display Name',
			k_auto_login = 'Auto Login',
			k_steam = 'Steam',
			k_discord = 'Discord',
			k_link_discord = 'Link Discord',
			k_unlink_discord = 'Unlink Discord',
			k_tos_title = 'Terms of Service & Privacy Policy',
			k_tos_first_time_1 = 'By accepting, you will register an account with',
			k_tos_first_time_2 = 'Balatro Multiplayer using your Steam account.',
			k_tos_first_time_3 = 'Please read and accept the Terms of Service and Privacy Policy.',
			k_tos_update_1 = 'The Terms of Service and Privacy Policy have been updated.',
			k_tos_update_2 = 'Please review and accept them to continue.',
			b_open_download_page = 'Open Download Page',
			b_retry_connection = 'Retry Connection',
			b_log_in = 'Log In',
			b_view_tos = 'View Terms of Service',
			b_view_privacy = 'View Privacy Policy',
			b_i_accept = 'I Accept',
			b_i_decline = 'I Decline',
			b_create_lobby_cap = { 'CREATE', 'LOBBY' },
			b_join_lobby_cap = 'JOIN LOBBY',
			b_by_code_cap = 'BY CODE',
			b_from_clipboard_cap = 'FROM CLIPBOARD',
			b_find_game_cap = 'FIND GAME',
			b_open_lobby_cap = { 'OPEN', 'LOBBY' },
			b_lobby_options_cap = { 'LOBBY', 'OPTIONS' },
			b_leave_lobby_cap = { 'LEAVE', 'LOBBY' },
		},
	},
	descriptions = {
		Other = {
			-- ── The Order: Skip Tags ────────────────────────────────────────────
			to_p1t1 = { name = 'Uncommon Tag', text = {
				'{C:attention}Uncommon Tags{} have a game-long',
				'{C:chips}Joker queue{} separate from the shop.',
				' ',
				'Only Uncommon skips advance this',
				'queue — jokers from it are {C:attention}hidden{}',
				'from your opponent.',
				' ',
				'Often taken for extra variance on',
				'{C:attention}Idol{}, {C:attention}Dusk{}, or {C:attention}Mime{}.',
			}},
			to_p1t2 = { name = 'Voucher Tag', text = {
				'{C:attention}Voucher Tags{} advance the',
				'{C:chips}Voucher queue{} in the same way',
				'that seeing another Ante does.',
				' ',
				'See the {C:attention}Shop Queue{} page for',
				'detailed examples.',
			}},
			to_p1t3 = { name = 'Riff-raff / Top Up', text = {
				'Both {C:attention}Riff-Raff{} and {C:attention}Top Up Tag{}',
				'draw from the same {C:chips}Common{}',
				'{C:chips}Joker queue{}.',
				' ',
				'This is {C:red}NOT{} the shop queue —',
				'jokers from it will {C:red}never{} appear',
				'for your opponent.',
			}},
			to_p1t4 = { name = 'Orbital Tag', text = {
				'Only change is standardization',
				'between {C:attention}Mac{} and {C:attention}Windows{} clients.',
				' ',
				'Note: can still desync if players',
				'have different hands unlocked.',
			}},
			to_p1t5 = { name = 'Rare Tag / Wraith', text = {
				'{C:attention}Rare Tags{} share a game-long queue',
				'with the {C:spectral}Wraith{} Spectral card.',
				' ',
				'This queue is separate from the',
				'shop. Only {C:attention}Rare skips{} and',
				'{C:spectral}Wraith{} cards can advance it.',
			}},
			-- ── The Order: Consumables ──────────────────────────────────────────
			to_p2t1 = { name = 'Aura', text = {
				'The {C:spectral}Aura{} Spectral card works on',
				'a {C:chips}game-long queue{}.',
				' ',
				'This is how Aura works in Vanilla.',
			}},
			to_p2t2 = { name = 'Rare Tag / Wraith', text = {
				'{C:spectral}Wraith{} shares a {C:chips}game-long queue{}',
				'with {C:attention}Rare Skips{}.',
				' ',
				'This queue is {C:red}NOT{} the shop queue.',
				'Only {C:attention}Rare skips{} and {C:spectral}Wraith{}',
				'cards can advance this queue.',
			}},
			to_p2t3 = { name = 'Judgement', text = {
				'On {C:attention}Orange Stake{} and above:',
				'{C:tarot}Judgement{} draws Jokers from its',
				'own separate {C:chips}queue{}.',
				' ',
				'On other stakes: it takes the',
				'next Joker from the {C:chips}shop queue{}.',
			}},
			-- ── The Order: Card Modifiers ───────────────────────────────────────
			to_p3t1 = { name = 'Glass', text = {
				'Despite {C:tarot}Justice{} being {C:red}banned{},',
				'Glass cards are still available',
				'in Standard Packs and via the',
				'{C:spectral}Familiar{}, {C:spectral}Grim{}, and {C:spectral}Incantation{}',
				'Spectral cards.',
				' ',
				'Glass now gives {C:mult}1.5x Mult{} on',
				'trigger (was {C:attention}2x{} in Vanilla).',
				' ',
				'Glass breaks use a {C:chips}game-long queue{},',
				'independent of hand order.',
			}},
			to_p3t2 = { name = 'Lucky', text = {
				'Lucky cards work on {C:chips}2 game-long{}',
				'{C:chips}queues{}:',
				' ',
				'{C:green}1 in 5{} chance for {C:mult}+Mult{}',
				'{C:green}1 in 15{} chance for {C:money}+$20{}',
				' ',
				'This is the same as Vanilla.',
			}},
			to_p3t3 = { name = 'Purple Seal', text = {
				'{C:attention}Purple Seals{} take {C:tarot}Tarot{} cards',
				'from the {C:chips}Up Top Tarot queue{}.',
			}},
			-- ── The Order: Decks ────────────────────────────────────────────────
			to_p4t1 = { name = 'Orange Deck', text = {
				'{C:attention}Multiplayer Exclusive{}',
				' ',
				'Start with a {C:attention}Giga Standard Pack{}',
				'(see Packs page for details).',
				' ',
				'Start with {C:chips}2{} copies of',
				'The Hanged Man.',
			}},
			to_p4t2 = { name = 'Purple Deck', text = {
				'{C:attention}Multiplayer Exclusive{}',
				' ',
				'{C:green}+1 Voucher Slot{}.',
				' ',
				'During {C:attention}Ante 1{}, all Vouchers',
				'are {C:money}50% off{}.',
			}},
			-- ── The Order: Jokers ───────────────────────────────────────────────
			to_p5t1 = { name = 'Superposition +', text = {
				'{C:attention}Superposition{}, {C:attention}Vagabond{}, and',
				'{C:attention}Cartomancer{} give {C:tarot}Tarot{} cards',
				'from the {C:chips}Up Top Tarot Queue{}.',
			}},
			to_p5t2 = { name = 'Prob. Jokers', text = {
				'{C:attention}8-Ball{}, {C:attention}Business Card{}, {C:attention}Gros Michel{},',
				'{C:attention}Space Joker{}, {C:attention}Hallucination{}, and',
				'{C:attention}Cavendish{} use a {C:chips}game-long{}',
				'{C:chips}proc queue{}.',
				' ',
				'{C:attention}8-Ball{} and {C:attention}Hallucination{} take from',
				'the {C:chips}Up Top Tarot Queue{}.',
				' ',
				'{C:attention}Oops! All 6s{} doubles proc chance.',
			}},
			to_p5t3 = { name = 'Golden Ticket', text = {
				'Changed from Vanilla:',
				' ',
				'Rarity: {C:attention}Uncommon{} (was {C:attention}Common{})',
				'Payout: {C:money}+$3{} per Gold card (was {C:red}+$4{})',
				'No longer requires a Gold card',
				'in deck to appear in shop.',
			}},
			to_p5t4 = { name = 'Seance / Sixth Sense', text = {
				'{C:attention}Seance{} and {C:attention}Sixth Sense{} take',
				'{C:spectral}Spectral{} cards from the',
				'{C:chips}Up Top Spectral Queue{}.',
				' ',
				'{C:attention}Invisible Joker{}, {C:attention}Ancient Joker{},',
				'{C:attention}Sock and Buskin{}, and {C:attention}Photograph{}',
				'work as expected.',
			}},
			to_p5t5 = { name = 'Riff-Raff / Top Up', text = {
				'Both {C:attention}Riff-Raff{} and {C:attention}Top Up Tag{}',
				'draw from the same {C:chips}Common{}',
				'{C:chips}Joker queue{}.',
				' ',
				'This is {C:red}NOT{} the shop queue —',
				'jokers here will {C:red}never{} appear',
				'for your opponent.',
			}},
			to_p5t6 = { name = 'To Do List', text = {
				'{C:attention}To Do List{} is standardized',
				'between {C:attention}Mac{} and {C:attention}Windows{} clients.',
				' ',
				'If players have different hands',
				'unlocked, they may still target',
				'different hand types.',
			}},
			to_p5t7 = { name = 'Invisible Joker', text = {
				'Variance reduced between players:',
				' ',
				'If both share {C:attention}N{} jokers, the extra',
				'joker is hit at only {C:green}1/N{} chance;',
				'all others copy what both players',
				'share.',
				' ',
				'Previously could copy any joker',
				'position independently.',
			}},
			to_p5t8 = { name = 'Bloodstone', text = {
				'{C:attention}Bloodstone{} and similar prob.',
				'jokers divide the proc field',
				'equally.',
				' ',
				'Position is determined by how',
				'recently the joker was obtained.',
			}},
			-- ── The Order: Misc ─────────────────────────────────────────────────
			to_p6t1 = { name = 'Hand Smoothing', text = {
				'Ante-based card draws from Vanilla',
				'have been changed to {C:attention}Round-based{}',
				'draws instead.',
				' ',
				'This makes draws slightly more',
				'consistent across all rounds.',
				' ',
				'Note: this effect is difficult',
				'to measure in practice.',
			}},
			-- ── The Order: Packs ────────────────────────────────────────────────
			to_p7t1 = { name = 'Arcana / Spectral', text = {
				'{C:tarot}Arcana{}, {C:planet}Celestial{}, and {C:spectral}Spectral{}',
				'packs each draw from their own',
				'respective consumable {C:chips}Pack queue{}.',
				' ',
				'See the {C:attention}Shop Queue{} page for',
				'in-depth examples.',
			}},
			to_p7t2 = { name = 'Buffoon Pack', text = {
				'{C:attention}Buffoon Packs{} draw directly from',
				'the {C:chips}Shop Queue{} (Joker sub-queue):',
				' ',
				'Normal Buffoon: next {C:chips}2{} Jokers',
				'Jumbo / Mega Buffoon: next {C:chips}4{}',
			}},
			to_p7t3 = { name = 'Standard Pack', text = {
				'{C:attention}Standard Packs{} draw from a',
				'{C:chips}game-long Playing Card queue{}.',
				' ',
				'This queue is separate from the',
				'{C:attention}Magic Trick{} Playing Card queue.',
				' ',
				'Order matters: opening a {C:attention}Normal{}',
				'before a {C:attention}Jumbo{} may split desired',
				'cards across both packs.',
			}},
			-- ── The Order: Shop Queue ───────────────────────────────────────────
			to_p8t1 = { name = 'Overview', text = {
				'The {C:chips}Shop Queue{} differs from',
				'Vanilla in several key ways:',
				' ',
				'Main shop has {C:attention}7 sub-queues{}',
				'(Jokers, Tarots, Planets, etc.)',
				'Pack shop has its own {C:chips}queue{}',
				'Voucher shop has its own {C:chips}queue{}',
				' ',
				'Skipping does {C:red}NOT{} advance the',
				'queue for your opponent.',
			}},
			to_p8t2 = { name = 'Sub-Queues', text = {
				'The Main Shop has {C:attention}7 sub-queues{}:',
				' ',
				'• {C:chips}Common Joker Queue{}',
				'• {C:chips}Uncommon Joker Queue{}',
				'• {C:chips}Rare Joker Queue{}',
				'• {C:chips}Up Top Tarot Queue{}',
				'• {C:chips}Up Top Planet Queue{}',
				'• {C:chips}Up Top Spectral Queue{}',
				'• {C:chips}Playing Card Queue{}',
				' ',
				'Each shop/reroll progresses the',
				'revealed sub-queues for that roll.',
			}},
			to_p8t3 = { name = 'How It Works', text = {
				'If {C:attention}Player 1{} skips and {C:attention}Player 2{}',
				'buys, {C:attention}Player 1{} will see the same',
				'packs as {C:attention}Player 2{}, just one blind',
				'later.',
				' ',
				'Rerolling advances the queue for',
				'that player {C:attention}only{}.',
			}},
			-- ── The Order: Vouchers ─────────────────────────────────────────────
			to_p9t1 = { name = 'Vouchers', text = {
				'No vouchers are changed from',
				'Vanilla itself.',
				' ',
				'However, when vouchers appear',
				'in the shop, the {C:chips}Voucher queue{}',
				'has been modified.',
				' ',
				'See the {C:attention}Shop Queue{} page for',
				'details.',
			}},
		},
	},
}
